# This is a basic workflow to help you get started with Actions

name: Make model

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@main
      - name: build application
        run: |
         cd release/src-ra-5010
         make model rt-mir4a
